# Generated by Django 5.2.8 on 2025-11-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovementReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('movement_type', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('source_location', models.CharField(max_length=255, null=True)),
                ('destination_location', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Movement History',
                'verbose_name_plural': 'Movement History',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('warehouse', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('total_qty', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
            options={
                'verbose_name': 'Stock Summary',
                'verbose_name_plural': 'Stock Summary',
                'managed': False,
            },
        ),
    ]
