# Generated by Django 5.2.8 on 2025-11-22 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdjustmentEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_number', models.CharField(max_length=50, unique=True)),
                ('system_quantity', models.DecimalField(decimal_places=3, help_text='Current quantity in system', max_digits=15)),
                ('counted_quantity', models.DecimalField(decimal_places=3, help_text='Actual counted quantity', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('adjustment_quantity', models.DecimalField(decimal_places=3, help_text='Difference (counted - system)', max_digits=15)),
                ('reason', models.CharField(choices=[('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('FOUND', 'Found'), ('PHYSICAL_COUNT', 'Physical Count'), ('QUALITY_ISSUE', 'Quality Issue'), ('OTHER', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adjustment_entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
