# Generated by Django 5.2.8 on 2025-11-22 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adjustments', '0001_initial'),
        ('products', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adjustmententry',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adjustmententry',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='warehouse.location'),
        ),
        migrations.AddField(
            model_name='adjustmententry',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='products.product'),
        ),
        migrations.AddField(
            model_name='adjustmententry',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adjustmententry',
            index=models.Index(fields=['adjustment_number'], name='adjustment__adjustm_66ef49_idx'),
        ),
        migrations.AddIndex(
            model_name='adjustmententry',
            index=models.Index(fields=['status', 'created_at'], name='adjustment__status_c5777c_idx'),
        ),
    ]
