# Generated by Django 5.2.7 on 2025-11-22 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIPT', 'Receipt'), ('DELIVERY', 'Delivery'), ('TRANSFER', 'Internal Transfer'), ('ADJUSTMENT', 'Adjustment'), ('OPENING', 'Opening Balance')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Positive number. Direction is decided by movement_type.', max_digits=12)),
                ('uom', models.CharField(blank=True, help_text='Unit of measure code (e.g., PCS, KG).', max_length=20)),
                ('document_type', models.CharField(blank=True, help_text="Type of source document e.g. 'RECEIPT', 'DELIVERY', 'TRANSFER'.", max_length=50)),
                ('document_number', models.CharField(blank=True, help_text='External or internal reference number.', max_length=100)),
                ('note', models.TextField(blank=True, help_text='Optional remark for this movement.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='warehouse.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='warehouse.location')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product'], name='stock_ledge_product_caef71_idx'), models.Index(fields=['movement_type'], name='stock_ledge_movemen_e3d3f8_idx'), models.Index(fields=['document_type', 'document_number'], name='stock_ledge_documen_524f2b_idx')],
            },
        ),
    ]
