# Generated by Django 5.2.7 on 2025-11-22 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('stock_ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='document_type',
            field=models.CharField(blank=True, help_text="e.g. 'RECEIPT', 'DELIVERY', 'TRANSFER'.", max_length=50),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='uom',
            field=models.ForeignKey(blank=True, help_text='Unit of measure for this movement. Defaults from product.', null=True, on_delete=django.db.models.deletion.PROTECT, to='products.unitofmeasure'),
        ),
    ]
