# Generated by Django 5.2.8 on 2025-11-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_ledger', '0002_alter_stockmovement_document_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=1, help_text='Positive number. Direction is decided by movement_type.', max_digits=12),
        ),
    ]
