# Generated by Django 5.2.8 on 2025-11-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_ledger', '0003_alter_stockmovement_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='is_auto',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='document_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='document_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
