# Generated by Django 5.2.8 on 2025-11-22 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transfers', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferorder',
            name='destination_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='warehouse.location'),
        ),
        migrations.AddField(
            model_name='transferorder',
            name='source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='warehouse.location'),
        ),
        migrations.AddField(
            model_name='transferorder',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferline',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='transfers.transferorder'),
        ),
        migrations.AddIndex(
            model_name='transferorder',
            index=models.Index(fields=['transfer_number'], name='transfer_or_transfe_6a6bea_idx'),
        ),
        migrations.AddIndex(
            model_name='transferorder',
            index=models.Index(fields=['status', 'created_at'], name='transfer_or_status_ba9e2b_idx'),
        ),
    ]
