# Generated by Django 5.2.8 on 2025-11-22 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryorder',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='source_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='warehouse.location'),
        ),
        migrations.AddField(
            model_name='deliveryorder',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='validated_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryline',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='deliveries.deliveryorder'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['delivery_number'], name='delivery_or_deliver_75c3be_idx'),
        ),
        migrations.AddIndex(
            model_name='deliveryorder',
            index=models.Index(fields=['status', 'created_at'], name='delivery_or_status_30ef07_idx'),
        ),
    ]
