# Generated by Django 5.2.8 on 2025-11-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_vendor_alter_receipt_receive_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='reference',
            field=models.CharField(blank=True, help_text='Auto-generated receipt number', max_length=50, null=True, unique=True),
        ),
    ]
