# Generated by Django 5.2.8 on 2025-11-22 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Auto-generated delivery number', max_length=50, unique=True)),
                ('delivery_address', models.CharField(help_text='Where the goods are delivered', max_length=200)),
                ('operation_type', models.CharField(default='Customer Delivery', help_text='Customer / Internal Transfer / Disposal', max_length=50)),
                ('schedule_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('WAITING', 'Waiting for Stock'), ('READY', 'Ready to Deliver'), ('DONE', 'Delivered')], default='DRAFT', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='deliveries.delivery')),
                ('location', models.ForeignKey(help_text='Stock will be deducted from this location', on_delete=django.db.models.deletion.PROTECT, to='warehouse.location')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
        ),
    ]
