# Generated by Django 5.2.8 on 2025-11-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        ('receipts', '0003_alter_receipt_reference'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='operation_type',
        ),
        migrations.AddField(
            model_name='delivery',
            name='deliver_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='receipts.vendor'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='reference',
            field=models.CharField(blank=True, help_text='Auto-generated delivery number', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('READY', 'Ready'), ('DONE', 'Done')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryline',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.location'),
        ),
    ]
